fix: execution blockers, unbound vars, incorrect vars, set +/-e around child process, etc.

diff --git a/owrt-build-all b/owrt-build-all
--- a/owrt-build-all
+++ b/owrt-build-all
@@ -58,7 +58,6 @@ SCRIPT_NAME=$(basename "$REAL_PATH")
 
 
 # Import lib/common.sh (bootstrap)
-log_debug "4" "[${SCRIPT_NAME}]: Sourcing 'lib/common.sh'"
 if ! source "$SCRIPT_DIR/lib/common.sh"; then
     echo " >>> ❌ CRITICAL: Unable to source lib/common.sh - Aborting." >&2
     exit 1
@@ -107,6 +106,7 @@ for config_file in "${all_configs[@]}"; do
         log_summary " >>> ⏭️  Skipping $(basename "$config_file"): Not enabled for batch build."
         log_debug "1" "Skipped config: '$config_file' - OWRTDS_ENABLE_BATCH_BUILD: '$OWRTDS_ENABLE_BATCH_BUILD'"
         ((BUILD_SKIPPED++)) || true
+        ((BUILD_TOTAL++)) || true
         continue
     fi
 
@@ -117,8 +117,12 @@ for config_file in "${all_configs[@]}"; do
     log_debug "1" "executing '$SCRIPT_DIR/owrt-build --config $config_file $@ -mc -uf -ni'"
 
     # Run the main script (pass in parameters from user, force non-interactive, ignoring --config/-c)
-    ( "$SCRIPT_DIR"/owrt-build --config "$config_file" "$@" -mc -uf -ni )
+    set +e
+    "$SCRIPT_DIR"/owrt-build --config "$config_file" "$@" -mc -uf -ni &
+    BUILD_PID=$!
+    wait $BUILD_PID
     BUILD_EXIT_CODE=$?
+    set -e
 
     ((BUILD_TOTAL++)) || true
 
@@ -128,7 +132,7 @@ for config_file in "${all_configs[@]}"; do
         log_debug "1" "$BUILD_TOTAL of $TOTAL_TO_BUILD succeeded: '$config_file'"
     else
         ((BUILD_FAILED++)) || true
-        log_summary " >>> ❌ Build #$BUILD_TOTAL of $TOTAL_TO_BUILD failed: $(basename "$config_file") (Exit Code: $EXIT_CODE)"
+        log_summary " >>> ❌ Build #$BUILD_TOTAL of $TOTAL_TO_BUILD failed: $(basename "$config_file") (Exit Code: $BUILD_EXIT_CODE)"
         log_debug "1" "$BUILD_TOTAL of $TOTAL_TO_BUILD failed: '$config_file'"
     fi
 
@@ -151,7 +155,7 @@ echo "  🏁  BATCH PROCESS REPORT"
 echo " =================================================================="
 echo "  Total Configs Processed:  $BUILD_TOTAL of $TOTAL_TO_BUILD"
 echo "  ✅ Successful Builds:     $BUILD_SUCCESS"
-echo "  ✅ Successful Builds:     $BUILD_SKIPPED"
+echo "  🔄 Skipped Builds:        $BUILD_SKIPPED"
 echo "  ❌ Failed Builds:         $BUILD_FAILED"
 echo " =================================================================="
 
